import { type InferSelectModel } from "drizzle-orm"
import { pgTable, serial, text } from "drizzle-orm/pg-core"

export const characters = pgTable("characters", {
  // Needs to reference a user_id that is generated by Clerk
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull(),
  // createdAt: timestamp("created_at").notNull().defaultNow(),
})
