module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "^@fortawesome/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/(types|components|styles|hooks)(/.*)?$",
    "",
    "^@/(ui|app|lib|data|paths|utils)(/.*)?$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
}
